version: '3'
services:
# services
  db:
    container_name: db
    image: "postgres"
    environment:
      POSTGRES_DB: SystemEventsDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - 5432
    expose:
      - 5432
    networks:
      - events
  event-service-db:
    container_name: event-service-db
    image: "postgres"
    environment:
      POSTGRES_DB: EventDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - 5432
    expose:
      - 5432
    networks:
      - events
  user-service-db:
    container_name: user-service-db
    image: "postgres"
    environment:
      POSTGRES_DB: UserDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - 5432
    expose:
      - 5432
    networks:
          - events
  user-ticket-service-db:
    container_name: user-ticket-service-db
    image: "postgres"
    environment:
      POSTGRES_DB: UserTicketDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - 5432
    expose:
      - 5432
    networks:
          - events
  notification-service-db:
    container_name: notification-service-db
    image: "postgres"
    environment:
      POSTGRES_DB: NotificationServiceDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - 5432
    expose:
      - 5432
    networks:
          - events
  eureka-service:
    container_name: eureka-service
    build:
      context: ./EurekaService/
      dockerfile: Docker
    image: eureka-service:latest
    restart: always
    links:
      - db:db
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - events
  system-events-service:
    container_name: system-events-service
    build:
      context: ./SystemEvents/
      dockerfile: Docker
    image: system-events:latest
    restart: always
    links:
      - eureka-service:eureka-service
      - db:db
    expose:
      - 8085
    ports:
      - 8085:8085 
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=SystemEventsDatabase
      - DATABASE_PORT=5432
    depends_on:
      - db 
      - eureka-service
    networks:
      - events
    
networks:
  events:
    driver: bridge