version: '3'
services:
# services
  db:
    container_name: db
    image: "postgres"
    environment:
      POSTGRES_DB: SystemEventsDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - 5432
    expose:
      - 5432
    networks:
      - events
  
  event-service-db:
    container_name: event-service-db
    image: "postgres"
    environment:
      POSTGRES_DB: EventDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - 5432
    expose:
      - 5432
    networks:
      - events
  
  user-service-db:
    container_name: user-service-db
    image: "postgres"
    environment:
      POSTGRES_DB: UserDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - 5432
    expose:
      - 5432
    networks:
      - events
  
  user-ticket-service-db:
    container_name: user-ticket-service-db
    image: "postgres"
    environment:
      POSTGRES_DB: UserTicketDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - 5432
    expose:
      - 5432
    networks:
      - events
      
  notification-service-db:
    container_name: notification-service-db
    image: "postgres"
    environment:
      POSTGRES_DB: NotificationServiceDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - 5432
    expose:
      - 5432
    networks:
      - events


  eureka-service:
    container_name: eureka-service
    build:
      context: ./EurekaService/
      dockerfile: Docker
    image: eureka-service:latest
    restart: always
    links:
      - db:db
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - events

  system-events-service:
    container_name: system-events-service
    build:
      context: ./SystemEvents/
      dockerfile: Docker
    image: system-events:latest
    restart: always
    links:
      - eureka-service:eureka-service
      - db:db
    expose:
      - 8085
    ports:
      - 8085:8085 
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=SystemEventsDatabase
      - DATABASE_PORT=5432
    depends_on:
      - db 
      - eureka-service
    networks:
      - events

  user-service:
    container_name: user-service
    build:
      context: ./UserService/
      dockerfile: Docker
    image: user-service:latest
    restart: always
    links:
      - eureka-service:eureka-service
      - user-service-db:user-service-db
    expose:
      - 8080
    ports:
      - 8080:8080 
    environment:
      - DATABASE_HOST=user-service-db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=UserDatabase
      - DATABASE_PORT=5432
    depends_on:
      - user-service-db 
      - eureka-service
    networks:
      - events
  user-ticket-service:
    container_name: user-ticket-service
    build:
      context: ./UserTicketService/
      dockerfile: Docker
    image: user-ticket-service:latest
    restart: always
    links:
      - eureka-service:eureka-service
      - user-ticket-service-db:user-ticket-service-db
    expose:
      - 8081
    ports:
      - 8081:8081 
    environment:
      - DATABASE_HOST=user-ticket-service-db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=UserTicketDatabase
      - DATABASE_PORT=5432
    depends_on:
      - user-ticket-service-db 
      - eureka-service
    networks:
      - events

  event-service:
    container_name: event-service
    build:
      context: ./EventService/
      dockerfile: Dockerfile
    image: event-service:latest
    restart: always
    links:
      - eureka-service:eureka-service
      - event-service-db:event-service-db
    expose:
      - 8082
    ports:
      - 8082:8082 
    environment:
      - DATABASE_HOST=event-service-db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=EventDatabase
      - DATABASE_PORT=5432
    depends_on:
      - event-service-db 
      - eureka-service
    networks:
      - events

  events-frontend:
    container_name: events-frontend
    build:
      context: ./Events-Frontend/
      dockerfile: Dockerfile
    image: events-frontend:latest
    restart: always
    #links:
    #  - eureka-service:eureka-service
    #  - event-service-db:event-service-db
    expose:
      - 4200
    ports:
      - 4200:4200 
    #environment:
      #- DATABASE_HOST=event-service-db
      #- DATABASE_USER=postgres
      #- DATABASE_PASSWORD=password
      #- DATABASE_NAME=EventDatabase
      #- DATABASE_PORT=5432
    #depends_on:
      #- event-service-db 
      #- eureka-service
    networks:
      - events

networks:
  events:
    driver: bridge